import { Account } from "./types";

interface MetricEntry {
  metric_name: string;
  current_value: number;
  limit_value: number;
  unit: string | null;
}

interface AccountSeedEntry {
  id: string;
  name: string;
  context: string | null;
  usage_metrics: MetricEntry[];
  budget_report: { mrr: number; contract_value: number; tier: string; renewal_in_days: number; payment_status: string };
}

function m(metric_name: string, current_value: number, limit_value: number, unit: string | null = null): MetricEntry {
  return { metric_name, current_value, limit_value, unit };
}

export const accountSeedData: AccountSeedEntry[] = [
  { id: "AC-1", name: "TechCorp", context: "Strong engineering culture, evaluating AI tools. CS flagged as expansion candidate.", usage_metrics: [m("seats", 95, 100, "users"), m("invoices", 460, 500, "invoices/mo"), m("integrations", 8, 10, "active")], budget_report: { mrr: 4200, contract_value: 50400, tier: "Growth", renewal_in_days: 45, payment_status: "current" } },
  { id: "AC-2", name: "BioLabs", context: null, usage_metrics: [m("seats", 40, 100, "users"), m("invoices", 200, 500, "invoices/mo"), m("integrations", 2, 10, "active")], budget_report: { mrr: 1100, contract_value: 13200, tier: "Starter", renewal_in_days: 210, payment_status: "current" } },
  { id: "AC-3", name: "Arctic Ltd", context: "Payment consistently late. New CFO started Q1. CS reports declining engagement in last 3 months.", usage_metrics: [m("seats", 88, 100, "users"), m("invoices", 430, 500, "invoices/mo"), m("integrations", 9, 10, "active")], budget_report: { mrr: 3800, contract_value: 45600, tier: "Growth", renewal_in_days: 12, payment_status: "overdue" } },
  { id: "AC-4", name: "Nebula Systems", context: "Strategic account. Multi-year deal in discussion. Heavy API usage growing 20% MoM.", usage_metrics: [m("seats", 492, 500, "users"), m("invoices", 2400, 2500, "invoices/mo"), m("integrations", 22, 25, "active"), m("api_calls", 480000, 500000, "calls/mo")], budget_report: { mrr: 12500, contract_value: 150000, tier: "Enterprise", renewal_in_days: 88, payment_status: "current" } },
  { id: "AC-5", name: "Solaris Energy", context: null, usage_metrics: [m("seats", 12, 50, "users"), m("invoices", 150, 500, "invoices/mo"), m("integrations", 1, 5, "active")], budget_report: { mrr: 850, contract_value: 10200, tier: "Starter", renewal_in_days: 302, payment_status: "current" } },
  { id: "AC-6", name: "Velocity Logistics", context: "Acquired smaller competitor last month, expecting user count to double. Urgent capacity discussion needed.", usage_metrics: [m("seats", 105, 100, "users"), m("invoices", 510, 500, "invoices/mo"), m("integrations", 12, 10, "active")], budget_report: { mrr: 4500, contract_value: 54000, tier: "Growth", renewal_in_days: 5, payment_status: "current" } },
  { id: "AC-7", name: "Quantum Leap", context: null, usage_metrics: [m("seats", 28, 25, "users"), m("invoices", 85, 100, "invoices/mo"), m("integrations", 4, 5, "active")], budget_report: { mrr: 600, contract_value: 7200, tier: "Starter", renewal_in_days: 14, payment_status: "current" } },
  { id: "AC-8", name: "Blue Horizon", context: "Executive sponsor left company. New CTO reviewing all vendor contracts. High churn risk.", usage_metrics: [m("seats", 410, 500, "users"), m("invoices", 1800, 2500, "invoices/mo"), m("integrations", 15, 25, "active"), m("storage", 1.8, 2.0, "TB")], budget_report: { mrr: 11000, contract_value: 132000, tier: "Enterprise", renewal_in_days: 150, payment_status: "overdue" } },
  { id: "AC-9", name: "GreenLeaf Retail", context: "Holiday season approaching, historically spikes to 2x usage in Q4.", usage_metrics: [m("seats", 98, 100, "users"), m("invoices", 495, 500, "invoices/mo"), m("integrations", 10, 10, "active")], budget_report: { mrr: 4100, contract_value: 49200, tier: "Growth", renewal_in_days: 20, payment_status: "current" } },
  { id: "AC-10", name: "Titanium Mfg", context: null, usage_metrics: [m("seats", 210, 250, "users"), m("invoices", 1100, 1500, "invoices/mo"), m("integrations", 18, 20, "active")], budget_report: { mrr: 8200, contract_value: 98400, tier: "Growth", renewal_in_days: 60, payment_status: "current" } },
  { id: "AC-11", name: "Pinnacle Consulting", context: null, usage_metrics: [m("seats", 15, 20, "users"), m("invoices", 40, 100, "invoices/mo"), m("integrations", 2, 5, "active")], budget_report: { mrr: 550, contract_value: 6600, tier: "Starter", renewal_in_days: 240, payment_status: "current" } },
  { id: "AC-12", name: "Ironclad Security", context: "Compliance-driven org. Recently adopted our audit log feature. Interested in SOC2 integration.", usage_metrics: [m("seats", 480, 500, "users"), m("invoices", 2600, 2500, "invoices/mo"), m("integrations", 25, 25, "active"), m("audit_events", 950000, 1000000, "events/mo")], budget_report: { mrr: 13500, contract_value: 162000, tier: "Enterprise", renewal_in_days: 35, payment_status: "current" } },
  { id: "AC-13", name: "Skyline Real Estate", context: null, usage_metrics: [m("seats", 65, 100, "users"), m("invoices", 320, 500, "invoices/mo"), m("integrations", 4, 10, "active")], budget_report: { mrr: 3200, contract_value: 38400, tier: "Growth", renewal_in_days: 180, payment_status: "current" } },
  { id: "AC-14", name: "Apex Finance", context: "Top-tier account. CEO personally involved. Running POC for our new analytics module.", usage_metrics: [m("seats", 850, 1000, "users"), m("invoices", 4800, 5000, "invoices/mo"), m("integrations", 45, 50, "active"), m("api_calls", 2800000, 3000000, "calls/mo"), m("automation_runs", 45000, 50000, "runs/mo")], budget_report: { mrr: 25000, contract_value: 300000, tier: "Enterprise", renewal_in_days: 110, payment_status: "current" } },
  { id: "AC-15", name: "Swift Delivery", context: "Disputed last invoice. Finance team unresponsive to CS outreach.", usage_metrics: [m("seats", 48, 50, "users"), m("invoices", 490, 500, "invoices/mo"), m("integrations", 10, 10, "active")], budget_report: { mrr: 2100, contract_value: 25200, tier: "Growth", renewal_in_days: 3, payment_status: "overdue" } },
  { id: "AC-16", name: "Oceanic Data", context: null, usage_metrics: [m("seats", 120, 100, "users"), m("invoices", 600, 500, "invoices/mo"), m("integrations", 11, 10, "active")], budget_report: { mrr: 4800, contract_value: 57600, tier: "Growth", renewal_in_days: 25, payment_status: "current" } },
  { id: "AC-17", name: "Summit Peak Tech", context: null, usage_metrics: [m("seats", 12, 25, "users"), m("invoices", 40, 100, "invoices/mo"), m("integrations", 3, 5, "active")], budget_report: { mrr: 700, contract_value: 8400, tier: "Starter", renewal_in_days: 190, payment_status: "current" } },
  { id: "AC-18", name: "Nova Healthcare", context: "HIPAA-regulated. Exploring our enterprise SSO add-on. Slow procurement cycles (60-90 days).", usage_metrics: [m("seats", 950, 1000, "users"), m("invoices", 9800, 10000, "invoices/mo"), m("integrations", 48, 50, "active"), m("storage", 4.2, 5.0, "TB")], budget_report: { mrr: 32000, contract_value: 384000, tier: "Enterprise", renewal_in_days: 200, payment_status: "current" } },
  { id: "AC-19", name: "Urban Design Co", context: null, usage_metrics: [m("seats", 82, 100, "users"), m("invoices", 410, 500, "invoices/mo"), m("integrations", 7, 10, "active")], budget_report: { mrr: 3900, contract_value: 46800, tier: "Growth", renewal_in_days: 40, payment_status: "current" } },
  { id: "AC-20", name: "Firewall First", context: null, usage_metrics: [m("seats", 20, 20, "users"), m("invoices", 110, 100, "invoices/mo"), m("integrations", 6, 5, "active")], budget_report: { mrr: 950, contract_value: 11400, tier: "Starter", renewal_in_days: 12, payment_status: "current" } },
  { id: "AC-21", name: "Riverstone Law", context: null, usage_metrics: [m("seats", 45, 50, "users"), m("invoices", 210, 500, "invoices/mo"), m("integrations", 3, 10, "active")], budget_report: { mrr: 2800, contract_value: 33600, tier: "Growth", renewal_in_days: 320, payment_status: "current" } },
  { id: "AC-22", name: "Vanguard Media", context: "Rapid growth, headcount doubled in 6 months. Already over limits on all dimensions.", usage_metrics: [m("seats", 600, 500, "users"), m("invoices", 3000, 2500, "invoices/mo"), m("integrations", 30, 25, "active")], budget_report: { mrr: 15000, contract_value: 180000, tier: "Enterprise", renewal_in_days: 55, payment_status: "current" } },
  { id: "AC-23", name: "Terra Firma", context: "Internal reorganization. Main champion moved to different department.", usage_metrics: [m("seats", 5, 50, "users"), m("invoices", 12, 500, "invoices/mo"), m("integrations", 1, 10, "active")], budget_report: { mrr: 1200, contract_value: 14400, tier: "Growth", renewal_in_days: 15, payment_status: "overdue" } },
  { id: "AC-24", name: "Prism Analytics", context: null, usage_metrics: [m("seats", 180, 200, "users"), m("invoices", 950, 1000, "invoices/mo"), m("integrations", 15, 20, "active")], budget_report: { mrr: 6800, contract_value: 81600, tier: "Growth", renewal_in_days: 80, payment_status: "current" } },
  { id: "AC-25", name: "Evolve Education", context: "Academic pricing. Expanding to 3 new campuses next semester.", usage_metrics: [m("seats", 240, 250, "users"), m("invoices", 1400, 1500, "invoices/mo"), m("integrations", 19, 20, "active")], budget_report: { mrr: 7500, contract_value: 90000, tier: "Growth", renewal_in_days: 44, payment_status: "current" } },
  { id: "AC-26", name: "Atlas Mining", context: null, usage_metrics: [m("seats", 15, 25, "users"), m("invoices", 99, 100, "invoices/mo"), m("integrations", 5, 5, "active")], budget_report: { mrr: 800, contract_value: 9600, tier: "Starter", renewal_in_days: 2, payment_status: "current" } },
  { id: "AC-27", name: "Core Software", context: null, usage_metrics: [m("seats", 100, 100, "users"), m("invoices", 500, 500, "invoices/mo"), m("integrations", 10, 10, "active")], budget_report: { mrr: 4000, contract_value: 48000, tier: "Growth", renewal_in_days: 30, payment_status: "current" } },
  { id: "AC-28", name: "Lighthouse Labs", context: "Series C funded, hiring aggressively. Already 20% over all limits.", usage_metrics: [m("seats", 1200, 1000, "users"), m("invoices", 6000, 5000, "invoices/mo"), m("integrations", 55, 50, "active"), m("api_calls", 1200000, 1000000, "calls/mo")], budget_report: { mrr: 28000, contract_value: 336000, tier: "Enterprise", renewal_in_days: 10, payment_status: "current" } },
  { id: "AC-29", name: "Everest Insurance", context: null, usage_metrics: [m("seats", 42, 100, "users"), m("invoices", 180, 500, "invoices/mo"), m("integrations", 2, 10, "active")], budget_report: { mrr: 3100, contract_value: 37200, tier: "Growth", renewal_in_days: 220, payment_status: "current" } },
  { id: "AC-30", name: "Falcon Aerospace", context: "Government contractor. Long procurement cycles. Budget locked annually.", usage_metrics: [m("seats", 245, 250, "users"), m("invoices", 1490, 1500, "invoices/mo"), m("integrations", 20, 20, "active")], budget_report: { mrr: 8900, contract_value: 106800, tier: "Growth", renewal_in_days: 18, payment_status: "current" } },
  { id: "AC-31", name: "Moxie Marketing", context: null, usage_metrics: [m("seats", 19, 25, "users"), m("invoices", 75, 100, "invoices/mo"), m("integrations", 4, 5, "active")], budget_report: { mrr: 650, contract_value: 7800, tier: "Starter", renewal_in_days: 145, payment_status: "overdue" } },
  { id: "AC-32", name: "Zenith Corp", context: null, usage_metrics: [m("seats", 670, 1000, "users"), m("invoices", 2200, 5000, "invoices/mo"), m("integrations", 12, 50, "active")], budget_report: { mrr: 19500, contract_value: 234000, tier: "Enterprise", renewal_in_days: 340, payment_status: "current" } },
  { id: "AC-33", name: "Crestline Global", context: null, usage_metrics: [m("seats", 92, 100, "users"), m("invoices", 440, 500, "invoices/mo"), m("integrations", 9, 10, "active")], budget_report: { mrr: 4300, contract_value: 51600, tier: "Growth", renewal_in_days: 102, payment_status: "current" } },
  { id: "AC-34", name: "Bionic Solutions", context: null, usage_metrics: [m("seats", 28, 50, "users"), m("invoices", 300, 500, "invoices/mo"), m("integrations", 6, 10, "active")], budget_report: { mrr: 2900, contract_value: 34800, tier: "Growth", renewal_in_days: 15, payment_status: "current" } },
  { id: "AC-35", name: "Vivid Venture", context: null, usage_metrics: [m("seats", 22, 20, "users"), m("invoices", 95, 100, "invoices/mo"), m("integrations", 5, 5, "active")], budget_report: { mrr: 880, contract_value: 10560, tier: "Starter", renewal_in_days: 7, payment_status: "current" } },
  { id: "AC-36", name: "Oak & Iron", context: null, usage_metrics: [m("seats", 150, 200, "users"), m("invoices", 1200, 1000, "invoices/mo"), m("integrations", 15, 20, "active")], budget_report: { mrr: 7200, contract_value: 86400, tier: "Growth", renewal_in_days: 55, payment_status: "current" } },
  { id: "AC-37", name: "Silverline Web", context: null, usage_metrics: [m("seats", 5, 25, "users"), m("invoices", 10, 100, "invoices/mo"), m("integrations", 1, 5, "active")], budget_report: { mrr: 450, contract_value: 5400, tier: "Starter", renewal_in_days: 270, payment_status: "current" } },
  { id: "AC-38", name: "Fusion Dynamics", context: "IPO planned for Q3. All vendor contracts under legal review.", usage_metrics: [m("seats", 1100, 1000, "users"), m("invoices", 5500, 5000, "invoices/mo"), m("integrations", 52, 50, "active"), m("automation_runs", 82000, 75000, "runs/mo")], budget_report: { mrr: 30000, contract_value: 360000, tier: "Enterprise", renewal_in_days: 11, payment_status: "current" } },
  { id: "AC-39", name: "Alpha Biotech", context: null, usage_metrics: [m("seats", 75, 100, "users"), m("invoices", 490, 500, "invoices/mo"), m("integrations", 10, 10, "active")], budget_report: { mrr: 4600, contract_value: 55200, tier: "Growth", renewal_in_days: 38, payment_status: "current" } },
  { id: "AC-40", name: "Paradigm Shift", context: null, usage_metrics: [m("seats", 18, 25, "users"), m("invoices", 105, 100, "invoices/mo"), m("integrations", 6, 5, "active")], budget_report: { mrr: 920, contract_value: 11040, tier: "Starter", renewal_in_days: 62, payment_status: "overdue" } },
  { id: "AC-41", name: "Legacy Brands", context: null, usage_metrics: [m("seats", 40, 100, "users"), m("invoices", 200, 500, "invoices/mo"), m("integrations", 3, 10, "active")], budget_report: { mrr: 3400, contract_value: 40800, tier: "Growth", renewal_in_days: 150, payment_status: "current" } },
  { id: "AC-42", name: "Hyperion AI", context: "AI startup, growing fast. Heavy API user. Evaluating competitors.", usage_metrics: [m("seats", 95, 100, "users"), m("invoices", 520, 500, "invoices/mo"), m("integrations", 10, 10, "active"), m("api_calls", 920000, 1000000, "calls/mo")], budget_report: { mrr: 4700, contract_value: 56400, tier: "Growth", renewal_in_days: 5, payment_status: "current" } },
  { id: "AC-43", name: "Emerald City", context: null, usage_metrics: [m("seats", 200, 250, "users"), m("invoices", 800, 1500, "invoices/mo"), m("integrations", 12, 20, "active")], budget_report: { mrr: 8100, contract_value: 97200, tier: "Growth", renewal_in_days: 210, payment_status: "current" } },
  { id: "AC-44", name: "NorthStar Ltd", context: "Recently merged with another company. Integration ongoing, usage expected to shift significantly.", usage_metrics: [m("seats", 10, 100, "users"), m("invoices", 50, 500, "invoices/mo"), m("integrations", 1, 10, "active")], budget_report: { mrr: 3800, contract_value: 45600, tier: "Growth", renewal_in_days: 12, payment_status: "overdue" } },
  { id: "AC-45", name: "Vector Graphics", context: null, usage_metrics: [m("seats", 24, 25, "users"), m("invoices", 98, 100, "invoices/mo"), m("integrations", 5, 5, "active")], budget_report: { mrr: 900, contract_value: 10800, tier: "Starter", renewal_in_days: 4, payment_status: "current" } },
  { id: "AC-46", name: "CloudNine SaaS", context: "Platform partner. Co-marketing agreement in place. Very sticky integration.", usage_metrics: [m("seats", 880, 1000, "users"), m("invoices", 4900, 5000, "invoices/mo"), m("integrations", 49, 50, "active"), m("storage", 3.8, 5.0, "TB"), m("api_calls", 1900000, 2000000, "calls/mo")], budget_report: { mrr: 26000, contract_value: 312000, tier: "Enterprise", renewal_in_days: 95, payment_status: "current" } },
  { id: "AC-47", name: "Frontier Partners", context: null, usage_metrics: [m("seats", 110, 100, "users"), m("invoices", 550, 500, "invoices/mo"), m("integrations", 10, 10, "active")], budget_report: { mrr: 4900, contract_value: 58800, tier: "Growth", renewal_in_days: 14, payment_status: "current" } },
  { id: "AC-48", name: "Orbit Travel", context: null, usage_metrics: [m("seats", 35, 50, "users"), m("invoices", 150, 500, "invoices/mo"), m("integrations", 4, 10, "active")], budget_report: { mrr: 2700, contract_value: 32400, tier: "Growth", renewal_in_days: 180, payment_status: "current" } },
  { id: "AC-49", name: "Stonehenge Inc", context: null, usage_metrics: [m("seats", 10, 20, "users"), m("invoices", 20, 100, "invoices/mo"), m("integrations", 1, 5, "active")], budget_report: { mrr: 500, contract_value: 6000, tier: "Starter", renewal_in_days: 300, payment_status: "current" } },
  { id: "AC-50", name: "Delta Robotics", context: "Manufacturing vertical leader. Interested in custom SLA. Engineering team loves the product.", usage_metrics: [m("seats", 1020, 1000, "users"), m("invoices", 5100, 5000, "invoices/mo"), m("integrations", 55, 50, "active"), m("automation_runs", 120000, 100000, "runs/mo")], budget_report: { mrr: 31000, contract_value: 372000, tier: "Enterprise", renewal_in_days: 40, payment_status: "current" } },
];

export const accounts: Account[] = accountSeedData.map(({ id, name }) => ({ id, name }));
