export const historicalDealsData = [
  {
    deal_id: "D-001",
    industry: "SaaS / Developer Tools",
    company_size: "51-200",
    original_tier: "Growth",
    proposed_tier: "Enterprise",
    deal_size_usd: 96000,
    pitch_type: "usage-ceiling",
    pitch_summary: "Showed customer they were hitting seat limit monthly; framed Enterprise as removing growth friction.",
    main_objections: JSON.stringify(["price jump too large", "needs CFO sign-off"]),
    objection_handling: "Offered 2-month free trial on Enterprise tier; looped in their CFO with an ROI one-pager.",
    outcome: "won",
    time_to_close_days: 22,
    notes: "ROI framing was key. Pure feature pitch had failed 3 months prior.",
  },
  {
    deal_id: "D-002",
    industry: "Healthcare / MedTech",
    company_size: "201-500",
    original_tier: "Starter",
    proposed_tier: "Growth",
    deal_size_usd: 28800,
    pitch_type: "integration-value",
    pitch_summary: "Highlighted the 3 native integrations (EHR, Slack, SSO) only available on Growth.",
    main_objections: JSON.stringify(["compliance review needed", "IT bandwidth"]),
    objection_handling: "Provided SOC 2 docs upfront; offered free onboarding session for IT team.",
    outcome: "won",
    time_to_close_days: 41,
    notes: "Compliance docs are a must-have for healthcare. Send before they ask.",
  },
  {
    deal_id: "D-003",
    industry: "E-commerce",
    company_size: "11-50",
    original_tier: "Growth",
    proposed_tier: "Enterprise",
    deal_size_usd: 72000,
    pitch_type: "renewal-upsell",
    pitch_summary: "Timed expansion proposal to 30 days before renewal. Bundled extra invoice volume.",
    main_objections: JSON.stringify(["already locked budget for year", "not enough feature delta"]),
    objection_handling: "Offered to lock current pricing for 2 years if they upgraded now.",
    outcome: "lost",
    time_to_close_days: 18,
    notes: "Budget was genuinely frozen. Should have surfaced this 90 days out, not 30.",
  },
  {
    deal_id: "D-004",
    industry: "FinTech",
    company_size: "51-200",
    original_tier: "Growth",
    proposed_tier: "Enterprise",
    deal_size_usd: 110400,
    pitch_type: "usage-ceiling",
    pitch_summary: "Invoice volume was at 94% of limit. Projected breach date shown in demo.",
    main_objections: JSON.stringify(["wants multi-year discount", "legal review on DPA"]),
    objection_handling: "15% discount on 2-year commit; fast-tracked DPA with legal team.",
    outcome: "won",
    time_to_close_days: 30,
    notes: "Showing a projected breach date created urgency without pressure.",
  },
  {
    deal_id: "D-005",
    industry: "Logistics / Supply Chain",
    company_size: "201-500",
    original_tier: "Starter",
    proposed_tier: "Growth",
    deal_size_usd: 19200,
    pitch_type: "integration-value",
    pitch_summary: "Customer kept requesting features (API access, custom reports) only on Growth.",
    main_objections: JSON.stringify(["team not using current plan fully"]),
    objection_handling: "Ran a free 2-week activation sprint to improve adoption, then re-pitched.",
    outcome: "won",
    time_to_close_days: 55,
    notes: "Low adoption was a red flag. Fixing it first made the upsell natural, not pushy.",
  },
  {
    deal_id: "D-006",
    industry: "EdTech",
    company_size: "11-50",
    original_tier: "Growth",
    proposed_tier: "Enterprise",
    deal_size_usd: 60000,
    pitch_type: "renewal-upsell",
    pitch_summary: "Renewal timing, strong usage across all metrics.",
    main_objections: JSON.stringify(["budget cycle mismatch", "leadership change"]),
    objection_handling: "Offered a 3-month extension at current rate to bridge their budget cycle.",
    outcome: "lost",
    time_to_close_days: 12,
    notes: "Leadership change killed momentum. Should have mapped all stakeholders earlier.",
  },
] as const;
